/** 估價單 JSON Schema（內嵌，不依賴外部檔案） */
export const quotationSchema: Record<string, unknown> = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: 'quotation',
  title: '估價單 (Quotation)',
  description: 'POST /api/generate { reportType: "quotation", data: { ... } } — 中一刀紙張 241×140mm，9 欄版面',
  type: 'object',
  required: ['customer', 'docInfo', 'items', 'totals'],
  properties: {
    customer: {
      type: 'object',
      description: '客戶資訊',
      required: ['companyName'],
      properties: {
        companyName: { type: 'string', description: '公司名稱' },
        companyCode: { type: 'string', description: '公司編碼（如 "RC1025"）' },
        taxId: { type: 'string', description: '統一編號' },
        phone: { type: 'string', description: '電話號碼' },
        paymentMethod: { type: 'string', description: '收款方式（月結30天、現金等）' },
        invoiceAddress: { type: 'string', description: '發票地址' },
        shippingAddress: { type: 'string', description: '送貨地址' },
      },
    },
    docInfo: {
      type: 'object',
      description: '單據資訊',
      required: ['date', 'docNumber'],
      properties: {
        date: { type: 'string', description: '單據日期，格式 YYYY/MM/DD 或 YYYY-MM-DD' },
        docNumber: { type: 'string', description: '單據號碼' },
        invoiceNumber: { type: 'string', description: '發票號碼（選填）' },
      },
    },
    items: {
      type: 'array',
      description: '明細（9 欄：英文品名/貨品名稱/數量/單位/規格/單價/金額/批號/有效日期）',
      items: {
        type: 'object',
        required: ['productName', 'qty', 'unitPrice', 'amount'],
        properties: {
          englishName: { type: 'string', description: '英文品名' },
          productName: { type: 'string', description: '貨品名稱/中文品名' },
          qty: { type: 'number', description: '數量' },
          unit: { type: 'string', description: '單位（箱、盒、瓶等）' },
          spec: { type: 'string', description: '規格（如 "56粒/盒"）' },
          unitPrice: { type: 'number', description: '單價' },
          amount: { type: 'number', description: '金額（數量×單價）' },
          lotNumber: { type: 'string', description: '批號' },
          expiryDate: { type: 'string', description: '有效日期，格式 YYYY-MM-DD' },
        },
      },
    },
    totals: {
      type: 'object',
      description: '合計區（貨單總計 / 溢收 / 折讓 / 應收）',
      required: ['totalDue'],
      properties: {
        subtotal: { type: 'number', description: '貨單總計' },
        overpayment: { type: 'number', description: '溢收金額' },
        discount: { type: 'number', description: '折讓' },
        totalDue: { type: 'number', description: '應收合計' },
      },
    },
  },
  examples: [
    {
      customer: {
        companyName: '家赫藥局(宅配-月結)',
        companyCode: 'RC1025',
        phone: '02-28346453',
        invoiceAddress: '臺北市士林區忠義街80號1樓',
        shippingAddress: '臺北市士林區忠義街80號1樓',
      },
      docInfo: {
        date: '2026-02-10',
        docNumber: 'S00980-WH/OUT/01624',
      },
      items: [
        {
          englishName: 'Eliquis Film-Coated Tablet 5mg',
          productName: '(甲)(特)艾必克凝膜衣錠5毫克 56粒/盒\nBC26133100',
          qty: 2,
          unit: '盒',
          spec: '56粒/盒',
          unitPrice: 1420,
          amount: 2840,
          lotNumber: 'MF6287',
          expiryDate: '2027-09-29',
        },
        {
          englishName: 'REPAGLINIDE TABLETS 1MG "CYH"(安定)',
          productName: '(特)柔醣錠1毫克 900粒/盒\nAC572251G0',
          qty: 2,
          unit: '盒',
          spec: '900粒/盒',
          unitPrice: 888,
          amount: 1776,
          lotNumber: 'C74-0319',
          expiryDate: '2027-11-07',
        },
        {
          englishName: 'PATEAR EYE LOTIONS "PATRON"',
          productName: '派滴兒點眼液10毫升 10ML/瓶\nA022473429',
          qty: 20,
          unit: '瓶',
          spec: '10ML/瓶',
          unitPrice: 26,
          amount: 520,
          lotNumber: '1185E',
          expiryDate: '2028-11-03',
        },
      ],
      totals: {
        subtotal: 5136,
        totalDue: 5136,
      },
    },
  ],
};
