/** 銷貨單 JSON Schema（內嵌，不依賴外部檔案）— v0.3.7 對齊 Photo 2 九欄版面 */
export const salesDeliverySchema: Record<string, unknown> = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: 'sales-delivery',
  title: '銷貨單 (Sales Delivery Note)',
  description: 'POST /api/generate { reportType: "sales_delivery", data: { ... } } — 中一刀紙張 241×140mm，9 欄版面',
  type: 'object',
  required: ['company', 'customer', 'docInfo', 'items', 'totals'],
  properties: {
    company: {
      type: 'object',
      description: '公司（賣方）資訊，印在表頭',
      required: ['name'],
      properties: {
        name: { type: 'string', description: '公司名稱（表頭左上角）' },
        address: { type: 'string', description: '公司地址（表頭第二行）' },
        tel: { type: 'string', description: '電話（表頭第三行）' },
        fax: { type: 'string', description: '傳真（表頭第三行）' },
        code: { type: 'string', description: '公司編碼（表頭右上角，如 "A01"）' },
      },
    },
    customer: {
      type: 'object',
      description: '客戶（買方）資訊',
      required: ['companyName'],
      properties: {
        companyName: { type: 'string', description: '客戶公司名稱' },
        taxId: { type: 'string', description: '統一編號' },
        phone: { type: 'string', description: '電話號碼' },
        paymentMethod: { type: 'string', description: '收款方式（月結30天、現金等）' },
        invoiceAddress: { type: 'string', description: '裝貨地址' },
        shippingAddress: { type: 'string', description: '送貨地址' },
        companyCode: { type: 'string', description: '客戶代號（備用，也可放 company.code）' },
      },
    },
    docInfo: {
      type: 'object',
      description: '單據資訊',
      required: ['date', 'docNumber'],
      properties: {
        date: { type: 'string', description: '單據日期，格式 YYYY/MM/DD' },
        docNumber: { type: 'string', description: '單據號碼' },
        invoiceNumber: { type: 'string', description: '發票號碼（選填）' },
      },
    },
    items: {
      type: 'array',
      description: '銷貨明細（9 欄：英文品名/真品名稱/數量/單位/規格/單價/金額/批號/有效日期）',
      items: {
        type: 'object',
        required: ['productName', 'qty', 'unitPrice', 'amount'],
        properties: {
          englishName: { type: 'string', description: '英文品名（長名稱自動換行，欄寬 18 半形字元）' },
          productName: { type: 'string', description: '真品名稱/中文品名（長名稱自動換行，欄寬 16 半形字元 = 8 個中文字）' },
          qty: { type: 'number', description: '數量' },
          unit: { type: 'string', description: '單位（箱、盒、瓶等）' },
          specification: { type: 'string', description: '規格（如 "1000粒/盒"、"24入/箱"）' },
          unitPrice: { type: 'number', description: '單價' },
          amount: { type: 'number', description: '金額（數量×單價）' },
          lotNumber: { type: 'string', description: '批號' },
          expiryDate: { type: 'string', description: '有效日期，格式 YYYY-MM-DD 或 YYYY/MM/DD' },
        },
      },
    },
    totals: {
      type: 'object',
      description: '合計區（總計 / 折讓 / 收）',
      required: ['totalDue'],
      properties: {
        subtotal: { type: 'number', description: '總計（所有明細金額加總）' },
        discount: { type: 'number', description: '折讓' },
        totalDue: { type: 'number', description: '收（實收金額 = 總計 - 折讓）' },
      },
    },
    notes: {
      type: 'string',
      description: '附註（印在合計下方左側）',
    },
    pageNumber: {
      type: 'number',
      description: '目前頁碼（預設 1）',
    },
    totalPages: {
      type: 'number',
      description: '總頁數（預設 1）',
    },
  },
  examples: [
    {
      company: {
        name: '大裕國際有限公司',
        address: '台北市中山區南京東路三段100號5F',
        tel: '(02)2505-1234',
        fax: '(02)2505-5678',
        code: 'A01',
      },
      customer: {
        companyName: '全聯福利中心 民生店',
        taxId: '12345678',
        phone: '(02)2760-1234',
        paymentMethod: '月結30天',
        invoiceAddress: '台北市松山區民生東路五段200號',
        shippingAddress: '台北市松山區民生東路五段200號',
      },
      docInfo: {
        date: '2026/02/27',
        docNumber: 'SD-20260227-001',
        invoiceNumber: 'AB-12345678',
      },
      items: [
        {
          englishName: 'METHATOCORAL',
          productName: '(特)滿可復膠囊',
          qty: 192,
          unit: '盒',
          specification: '1000粒/盒',
          unitPrice: 1880,
          amount: 191040,
          lotNumber: '56A28T',
          expiryDate: '2028-06-12',
        },
        {
          englishName: 'VITAMIN B COMPLEX',
          productName: '維他命B群錠',
          qty: 50,
          unit: '瓶',
          specification: '100錠/瓶',
          unitPrice: 320,
          amount: 16000,
          lotNumber: '78B15K',
          expiryDate: '2027-12-31',
        },
        {
          englishName: 'CALCIUM CARBONATE TABLET',
          productName: '碳酸鈣嚼錠',
          qty: 30,
          unit: '盒',
          specification: '60錠/盒',
          unitPrice: 250,
          amount: 7500,
          lotNumber: '90C03M',
          expiryDate: '2028-03-15',
        },
      ],
      totals: {
        subtotal: 214540,
        discount: 540,
        totalDue: 214000,
      },
      notes: '請於收貨時確認數量及品質。',
    },
  ],
};
